apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-lb
  labels:
    {{ include "rabbitmq-chart.labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.amqpPort }}
    targetPort: amqp
    name: amqp
  - port: {{ .Values.service.streamPort }}
    targetPort: stream
    name: stream
  - port: {{ .Values.service.managementPort }}
    targetPort: management
    name: management
  selector:
    app: {{ include "rabbitmq-chart.name" . }}
